apiVersion: apps.mas.ibm.com/v1
kind: ManageApp
metadata:
  name: {{ .Values.masapp.instanceid }}
  namespace: {{ .Values.masapp.namespace }}
  labels:
    mas.ibm.com/applicationId: manage
    mas.ibm.com/instanceId: {{ .Values.masapp.instanceid }}
    {{- include "ibm-masapp-manage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec: {}
