apiVersion: apps.mas.ibm.com/v1
kind: ManageWorkspace
metadata:
  name: "{{ .Values.workspace.name }}"
  labels:
    mas.ibm.com/instanceId: "{{ .Values.masapp.instanceid }}"
    mas.ibm.com/workspaceId: "{{ .Values.masapp.workspaceid }}"
    mas.ibm.com/applicationId: "{{ .Values.masapp.appid }}"
    {{- include "ibm-masapp-manage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  bindings:
    jdbc: workspace-application
  components:
    base:
      version: latest
  settings:
    aio:
      install: true
    db:
      dbSchema: "{{ .Values.workspace.dbschema }}"
      {{- if .Values.masapp.reuse_db }}
      encryptionSecret: "{{ .Values.masapp.cr_secret_name }}"
      {{- end }}
      maxinst:
        {{- if .Values.masapp.demodata }}
        demodata: true
        {{- else }}
        demodata: false
        {{- end }}
        db2Vargraphic: true
        indexSpace: MAXINDEX
        tableSpace: MAXDATA
        bypassUpgradeVersionCheck: false

