# Default values for masauto-manage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Required values
ibm_entitlement_secret: ""
mas_instance_id: ""
mas_workspace_id: ""
db2_meta_storage_class: ""
db2_data_storage_class: ""

mas_app_settings_demodata: "false"
db2_instance_name: "db2w-manage"
mas_app_channel: "8.4.x"
mas_config_scope: "wsapp"
db2_dbname: "MANAGE"

mas_appws_jdbc_binding: "workspace-application"

